// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iggszpedbfpaeexskknp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZ3N6cGVkYmZwYWVleHNra25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTA4OTMsImV4cCI6MjA3MDg4Njg5M30.Wvoeysd9gSlmhbhcQHyBU6SuJjH7V_ww0AIdicGs-iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});