// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkxkhdfevzcinhshhvgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFreGtoZGZldnpjaW5oc2hodmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjMxMDUsImV4cCI6MjA3MjQzOTEwNX0.6aM20DlaW88Lp6oFR9e-B_KI88s9IgTGpRDsqBBzRZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});